### ISSUE TITLE
Three feature requests

### ISSUE THREAD

**Issue by gshotwell** [shafayetShafee/line-highlight#1]
Thanks so much for the great extension, it's super useful and I think they should include something similar in quarto proper. A few feature requests:

1) Consider following [the code annotation](https://quarto.org/docs/prerelease/1.3/code-annotation.html) pattern instead of having the user specify the line numbers
2) It would be great if this worked on syntactically formatted markdown blocks (the ones that use `.r` instead of `{r}` the main benefit of this is that you would be able to generate R code documentation without the R dependency
3) I modified the css to add a bold-and-blur hover annotation which might be good to include as an option. I think this is a bit more expressive on the web. 

```
/* for source-line-numbers */
div.sourceCode.cell-code:hover
pre
code.has-line-highlights
> span:not(.highlight-line) {
  opacity: 0.4;
}

div.sourceCode.cell-code:hover
pre
code.has-line-highlights
> span.highlight-line {
  font-weight: bold;
}
```

**Comment by shafayetShafee** [comment]
Hey, thanks for creating this issue with the features request 😀. All of them seem really useful and amazing options to have 🤩. But I have a very busy two weeks ahead. Therefore, I  will try to look into these thereafter.

However, the first suggested feature probably will require lots of thinking, because this extension makes use of [line-highlight.js](https://github.com/shafayetShafee/line-highlight/blob/main/_extensions/line-highlight/resources/js/line-highlight.js) which requires the line numbers 😅. The second and third options should probably be easy to implement.

And also I would appreciate PR with the above CSS changes 😀. Thanks!

**Comment by shafayetShafee** [comment]
@GShotwell, FYI I have implemented your second and third feature ideas in the latest release v1.1.0 of the extension. Check out the [rendered output](https://shafayetshafee.github.io/line-highlight/example.html#highlighting-on-markdown-formatted-codeblocks). Thanks for suggesting them.

**Comment by shafayetShafee** [comment]
But as said before,
> However, the first suggested feature probably will require lots of thinking, because this extension makes use of [line-highlight.js](https://github.com/shafayetShafee/line-highlight/blob/main/_extensions/line-highlight/resources/js/line-highlight.js) which requires the line numbers 😅. 

So implementing the first one would be difficult as per my current knowledge of pandoc lua filter 😅😓😔.

However, I think it would be better to close this issue for now and create a separate one for the first suggested feature specifically 🙂😀.

**Comment by gshotwell** [comment]
Looks great!
