### ISSUE TITLE
Doesn't work with `panel-tabset`

### ISSUE THREAD

**Issue by kdheepak** [shafayetShafee/line-highlight#15]
Thanks for making this extension and maintaining it! It is one of my favorite extensions for quarto!

The following code doesn't seem to work for me:

````
::: panel-tabset

## Example1

```{julia}
#| eval: false

@info "Open Database"
OpenDB() #<<
```

## Example2

```{julia}
#| eval: false

@info "Close Database"
CloseDB() #<<
```

:::
````

![image](https://user-images.githubusercontent.com/1813121/234073357-cea07f50-f4ef-45b7-9f61-6049c2d986ab.png)

Do you know if this can be supported?

**Comment by shafayetShafee** [comment]
Uhh, well it seems the extension actually making changes (necessary for enabling line highlighting) for the code blocks within the `panel-tabset`, but after that quarto-filter itself strips off all that changes keeping only the code texts, and returns a new code block with those texts along with other things to create `panel-tabset` (That's my understanding after doing a quick go through over [`panel-tabset.lua`](https://github.com/quarto-dev/quarto-cli/blob/86b22ca080cefca5efe8746972515bcd8f0d29df/src/resources/filters/quarto-pre/panel-tabset.lua)). And that's why in the final rendered output, line highlighting is not working for code-chunks within the `panel-tabset`.

Therefore, with this understanding, the solution is straightforward. **Just run `line-highlight` filter after the `quarto` filter**, which we can do as,

~~~
filters: 
  - quarto
  - line-highlight
~~~

## Full Reprex

~~~
---
title: "Untitled"
format: html
filters: 
  - quarto
  - line-highlight
---

## Quarto

::: panel-tabset

## Example1

```julia
@info "Open Database"
OpenDB() #<<
```

## Example2

```julia
@info "Close Database"
CloseDB() #<<
```

:::
~~~

<hr>

![image](https://user-images.githubusercontent.com/48413872/234089230-962116b0-b8b7-4e82-9a33-8b009dc7a4ce.png)

<hr>


**And note that, `line-highlight`  now works on non-executable code blocks too as you have requested in #2.  [See here](https://github.com/shafayetShafee/line-highlight#highlighting-on-markdown-formatted-codeblocks) on README for details.**

**Comment by kdheepak** [comment]
That's awesome! Works perfectly! Thank you so much!

**Comment by kdheepak** [comment]
Do you have a GitHub sponsors link? I'd like to donate to buy you a coffee as a gesture of my appreciation :)

**Comment by shafayetShafee** [comment]
Uhm, Not now currently. But I will let you know 😀. 

Also you can star this repo if you like this one 🙂.
