### ISSUE TITLE
Highlight lines in code blocks that are not executable

### ISSUE THREAD

**Issue by kdheepak** [shafayetShafee/line-highlight#2]
Thanks for writing and maintaining so many useful quarto plugins and extensions!

Something like this works great!

````
```{julia}
#| source-line-numbers: "2"
println("hello")
println("world")
```
````

Here's a screenshot of the markdown rendered using Quarto with your extension:

<img width="770" alt="image" src="https://user-images.githubusercontent.com/1813121/230733898-4aaa039e-d72f-4fef-95b3-4a57dd330754.png">

But this doesn't appear to work:

````
```julia
#| source-line-numbers: "2"
println("hello")
println("world")
```
````

Here's a screenshot of the markdown rendered in the same document:

<img width="770" alt="image" src="https://user-images.githubusercontent.com/1813121/230733903-bbf968a7-6450-4e7e-ac72-bec72a08f62e.png">

Do you know if this second option can work?

**Comment by shafayetShafee** [comment]
The second option does not work, because the extension currently detects only the html divs with the class `cell`, and code blocks written like the first option are rendered with the `cell` class while the second option generates html divs without the css class `cell` for the code blocks 😓😓.

However, you can make the code block in the first option not-executable using the chunk option `eval: false`, right 😅😉?

**Comment by kdheepak** [comment]
That works great! Thank you!

And thanks for the rapid response too!

**Comment by shafayetShafee** [comment]
Glad to know it worked. But keep an eye out for updates. I have plans to implement the second feature of this issue #1 which will enable the extension for your second option too (hopefully 😅).
